# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create ([
	{fullname: "Elise Barnes", username: "barnese3", email: "barnese3@go.stockton.edu", password: "password"},
	{fullname: "John Murphy", username: "johnm", email: "jmurphy@gmail.com", password: "password123"}
])

Post.create ([
	{user_id: 1, body: "Accommodation – There aren’t many hostels or campgrounds to be found in the Caribbean, but the ones that do exist will cost around $20 USD per night. A basic room in a 2-star budget hotel in a room that sleeps two starts around an $80 USD per night average. Airbnb is also available throughout the Caribbean and you can find entire homes (usually studio apartments) starting around a $50 USD per night average. You will find more inventory if you look around $95 USD or above, though. While there are a lot of islands in the Caribbean and prices vary widely, remember that overall, this is an expensive part of the world.

Food – Food typical of the Caribbean includes dishes with lots of beans, plantains, rice, sweet potatoes, coconut, pork beef, chicken, and fish. Prices vary considerably depending on which island you are on (Is it big? Small? Does it have a large local population? Or does it cater to tourists?) but you’re looking at between $10-20 USD for a meal at a restaurant. Prices go up from there. If you can find food at the local markets, those will cost around $5. My advice for the region: avoid restaurants near cruise ports and resorts, find the local markets, and cook your food as often as you can. Rarely are the fancy meals worth their exorbitant price!

Transportation – Bus services on the islands are inexpensive, rarely more than $3 USD. You can hitchhike safely around most of the islands too (save Jamaica, the Dominican Republic, Cuba, and Haiti). On islands without a bus system, a taxi may be the only form of transport with fares getting up to $15 USD for even a short journey. To get between islands, you’ll need your own boat or to fly. In the Lower Antilles, there are ferries that connect the island together since they aren’t too far apart but, generally speaking, flights are the most realistic option.

Activities – In general, tours, historical, and architectural attractions are relatively inexpensive ($5-20 USD), while diving trips usually costing a minimum of $125 USD. Snorkeling can be found as low as $20 USD for the day. Jet skiing will cost you about $65 USD for half an hour, and parasailing will be about $60 for 15 minutes. Admission to the Bob Marley Museum in Jamaica is $23 USD.

Suggested daily budget – $60-100 USD (Note: This is a suggested budget assuming you’re staying in a hostel, eating out a little, cooking most of your meals, and using local transportation. Using the budget tips below, you can always lower this number. However, if you stay in fancier accommodation or eat out more often, expect this to be higher!)", title: "Turks and Caicos", image: open("http://www.lamacchiatravel.com/sites/default/files/destinations/Turks-and-Caicos-Islands.jpg")},
	{user_id: 2, body: "Accommodation – Prices average 10-20 EUR a night for a hostel dorm room. You can find private rooms that sleep two ranging from 35-60 EUR. Hostels typically offer free linens, free WiFi, and a lot offer free breakfast. Budget hotels average around 50 and will include a private bathroom and some include an Irish breakfast (read, scone). In the bigger cities, especially Dublin, expect to pay a bit more. You could also try Airbnb, which has shared rooms for as low as 16 EUR per night and entire homes averaging about 50 EUR a night.

Food – Fast food items start at around 4 EUR, while a simple meal at a pub will set you back 9-14 EUR. A nicer meal, with a drink, will be upwards of 18 EUR. If you go out early to lunch or dinner, you’ll find many restaurants offer “early bird” specials where you can get good deals.  If you cook your meals, expect to pay 50-60 EUR per week for groceries that will include pasta, vegetables, chicken, and other basic foods. For the best value food, visit the pubs! Local meal, with local people, at local prices!

Transportation – Public transportation is first-rate in Ireland! Whether you’re on a bus or train, expect free WiFi, friendly drivers, and timely departures. Bus trips around Dublin cost about 2 EUR for a single journey. Longer bus journeys, such as Dublin to Belfast will cost around 17 EUR.  It costs about 45-65 EUR to get to Cork from Dublin by train and takes about 2.5 hours. It costs about 35-55 EUR to get to Galway from Dublin by train and takes about 3 hours.  Buses take about the same amount of time but will save you about 10 EUR. Taxis are expensive and, since most cities are extremely walkable, I suggest you avoid them.

Activities – Most museums throughout the country cost about 9-14 EUR. The Guinness Brewery is one of the few I would recommend, but the most expensive, costing 21 EUR at the door. Save 10 by booking online in advance (added bonus – you also get a fast pass to skip to the front during busy season). Day trips around the countryside will set you back 36 EUR or more.

Suggested daily budget – 40-60 EUR / $42-63 USD (Note: This is a suggested budget assuming you’re staying in a hostel, eating out a little, cooking most of your meals, and using local transportation. Using the budget tips below, you can always lower this number. However, if you stay in fancier accommodation or eat out more often, expect this to be higher!)", title: "Dublin, Ireland", image: open("http://www.chooseireland.com/wp-content/themes/kedar-theme/img/slider/slide1_sm.jpg")},
{user_id: 1, body: "Accommodation – Hostels start at 20 AUD per night for a dorm room, though they get as high as 40 in the big coastal cities. Private rooms with a double bed and a shared bathroom in hostels range between 80-100 AUD per night. For budget hotels, you are looking to spend at least around 75-95 AUD for a double room, private bathroom, TV, and breakfast. Larger, chain hotels cost closer to 200 AUD. Camping costs between 15-30 AUD per night (cheaper if you bring your own tent, more expensive if you’re parking an RV). Read more: My favorite hostels in Australia.

Food – Food isn’t cheap in Australia! Most decent restaurant entrees cost at least 20 AUD . Originally, I thought I was doing something wrong spending so much, but as many of my Aussie friends told me, “we just get screwed here.” If you cook your meals, expect to pay 100 AUD per week for groceries that will include pasta, vegetables, chicken, and other basic foodstuffs. Grab and go places cost around 8-10 AUD for sandwiches. Fast food is around 15 AUD for a meal (burger, fries, soda). The best value food are the Asian and Indian restaurants where you can get a really filling meal for under $10 AUD!

Transportation – Local city trains and buses cost 3-4 AUD. The easiest way to get around the country is via Greyhound. Passes begin at 145 AUD and go all the way to 3,000 AUD. There are also backpacker buses like the Oz Experience that have multi-city passes starting at 535 AUD (though I don’t like the Oz Experience and wouldn’t recommend it). The most popular and cheapest way to travel is to drive yourself. Campervan rentals start at 60 AUD per day and can also double as places to sleep. Flying can be very expensive due to limited competition, especially when going from coast to coast. I generally avoid flying in Australia unless I am pressed for time or there is a sale.

Activities — Multi-day activities and tours are expensive, generally costing 400-540 AUD. Day trips will cost about 135-230 AUD. For example, a one-day trip to the Great Barrier Reef can cost 230 AUD while a two-night sailing trip around the Whitsunday Islands can cost upwards of 540 AUD. A three-day trip to Uluru from Alice Springs is around 480 AUD. Walking tours are around 50 AUD and day trips to wine regions are between 150-200 AUD.

Suggested daily budget — $60-80 AUD / 43-57 USD (Note: This is a suggested budget assuming you’re staying in a hostel, eating out a little, cooking most of your meals, and using local transportation. This also depends greatly on the number of tours you do! Using the budget tips below, you can always lower this number. However, if you stay in fancier accommodation or eat out more often, expect this to be higher!)", title: "Sydney, Australia", image: open("https://secure.parksandresorts.wdpromedia.com/resize/mwImage/1/1200/600/90/secure.parksandresorts.wdpromedia.com/media/abd/refresh/asia-africa-australia/australia-vacations/adventures-by-disney-australia-day-02-opera-house.jpg")},
	{user_id: 2, body: "Accommodation – Hostels will cost you about 120-150 ZAR per night for a 10-20 bed dorm, or around to 250-300 ZAR per night for a 4-8 bed dorm. A private double room will cost between 300–450 ZAR. Free WiFi is standard, and many hostels also include free breakfast. If you have a tent, most will let you camp on their grounds. If you are looking for a hotel, budget hotels range from about 750-1,200 ZAR for a twin or double in big cities and get cheaper in more rural areas. For a hotel with free breakfast, expect to pay at least 900 ZAR. Airbnb is also an option around the country, though it’s most commonly available in larger urban areas. Prices for shared accommodation start around 300 ZAR per night, while an entire home or apartment will cost at least 800 ZAR (though average prices are closer to 1,800 ZAR). For those traveling with a tent, camp grounds can be found all around the country. Expect to pay between 90-400 ZAR per night, depending on the facilities and location.

Food – Restaurants in South Africa are pretty cheap. A meal at Nando’s or another fast-food chain will cost you about 50 ZAR per person. At a nicer restaurant, a 3-course meal with a wine costs about 225 ZAR per person. Expect to pay around 30 ZAR for a beer and 9 ZAR for a bottle of water. A bottle of wine at a restaurant or bar will cost 50-120 ZAR (for the bottle, not a glass!). The low-cost alternative to eating out is to buy groceries. A week’s worth of groceries for one person will cost around 500 ZAR. If you want to keep costs low, avoid expensive items like chicken, beef, and cheese.

Transportation – Greyhound and Baz Buses offer the most reliable public transportation and cost anywhere from 25–700 ZAR. A bus from Cape Town to Johannesburg, for example, will cost around 500 ZAR. Train rides are less common but more comfortable and safer than buses. Fare for a first class sleeper carriage is around 200–300 ZAR, depending on the distance.  If you plan on exploring a lot a small car can be rented for as little as 260 ZAR per day, including insurance and the fee to drop it off in a different city. Public transportation is available in the larger cities, though it is notoriously unreliable (and I actually wouldn’t recommend taking buses or vans within the cities). If you’re just trying to get around a big city, I recommend downloading the Uber app instead of taxis. Absolutely do not hitchhike!!

Activities – There are so many activities to choose from in South Africa. Hiking and nature-based activities are generally free (or close to it). Entrance fees to game reserves usually run about 100-300 ZAR per person. Full-day tours can cost anywhere from 400-2,000 ZAR, depending on what you’re doing. White water rafting, for example, will cost at least 550 ZAR (prices will vary depending on how long you go for, as multi-day tours are available). Diving will cost around 1,900 ZAR for a two-tank dive. In order to ensure that you’re getting the cheapest prices, book these through your hostel.

Suggested daily budget – 460 – 600 ZAR/35-45 USD (Note: This is a suggested budget assuming you’re staying in a hostel, eating out a little, cooking most of your meals, doing lots of free activities, keeping your drinking to a minimum, and using local transportation. Using the budget tips below, you can always lower this number. However, if you stay in fancier accommodation or eat out more often, expect this to be higher!)", title: "Cape Town, South Africa", image: open("https://cdn.passporthealthusa.com/wp-content/uploads/2017/07/advice-vaccines-south-africa.jpg?x61082")},
{user_id: 1, body: "Accommodation – You can find hostel dorm rooms as low as 24 PEN per night, although most are in the 40-50 PEN range. Expect to pay 70-150 PEN per night for a private room that sleeps two. A night in a 2-star budget hotel with the basic amenities in Peru starts around 40 PEN. On Airbnb, you can find shared rooms starting around 38 PEN and entire homes  starting at 135 PEN per night.

Food – You’ll find a wide range of food across Peru, with different specialties in each region. Ceviche is popular here and quinoa originated from this part of the world. Street stalls and markets have very cheap food (3-6 PEN) and in a sit-down restaurant you can get lunch and dinner menus for 12-20 PEN. For a Western meal in an average restaurant, you will pay 32-48 PEN in Lima and Cusco. Outside the big cities, you can usually find a set meal for about 10 PEN You can usually get a decent set meal for 10 PEN. If you plan on cooking, expect to pay 150 PEN per week for groceries that will include pasta, vegetables, chicken, and other basic foods.

Transportation – The usual price for a 10-hour bus journey is around 40 PEN depending on how nice the bus company is. A taxi around Lima should cost no more than 50-70 PEN. Lima has brand-new, clean intra-city buses. These buses are safe (ish- petty theft is common) and cost 0.50-3 PEN per trip. Microbuses (colectivos) run as well, and prices vary depending on the distance, but will always cost less than 2.50 PEN. They are a bit hectic and take some getting used to. Uber, the taxi alternative, operates in two cities in Peru: Arequipa and Lima.

Activities – Trip to archaeological sites are likely to be your biggest expensive with a day trip to Machu Picchu costing around 190 PEN. The Nasca Lines helicopter tour is relatively expensive at 415 PEN for 35 minutes in the air. Multi-day trips up the Inca Trail cost hundreds of dollars. However, entrances to museums outside of the major sites are under 38 PEN.

Suggested daily budget – 100-170 PEN / $30-50 USD (Note: This is a suggested budget assuming you’re staying in a hostel, eating at cheaper local restaurants and markets, and using local transportation. Using the budget tips below, you can always lower this number. However, if you stay in fancier accommodation or eat out more often, expect this to be higher!)", title: "Lima, Peru", image: open("https://www.fragomen.com/sites/default/files/styles/xl_image/public/portal/photos/Peru_Hero.jpg?itok=XDc6AhE-")},
{user_id: 2, body: "Accommodation – Dorm rooms will range from 15-40 EUR per night, depending on where you’re staying in the country, with Paris being on the higher end. Private rooms in hostels will cost around 75 EUR or more. Budget hotels begin around 60 EUR per night for a double room with free WiFi and air-conditioning. Accommodations are cheaper outside Paris, Bordeaux, and the French Riviera. Also look into renting rooms or apartments, through services like Airbnb. In an expensive city like Paris, this will be the best value. Airbnb rates start around 15 EUR for a shared room and 45 EUR for an entire apartment.

Food – Buying your own food in France can be very cheap and the best way to experience the country’s cuisine. The market is your friend! There are many bread, cheese, and meat shops around – and it’s how the French eat. They go to their local markets, buy food, and cook. You can make your own lunch for around 10 EUR for two people (including wine if you’re savvy enough). Pre-made sandwiches at cheap local shops will cost about 4-7 EUR. Conversely, eating at a restaurant will cost between 20-35 EUR for a meal including a glass of wine. If you shop for all your food, you can expect to spend around 45-65 EUR for a week’s worth of groceries,  but if you find a discount grocer like Aldi or Lidl, you’ll pay way less.

Transportation – The best way to get around France is via trains, but it can be expensive. Overnight trains cost the least, while the fast TGV lines (high-speed train) cost the most. Book ahead of time to get the best savings. Bought the day of or very close to departure, a train trip from Paris to Nice costs 160-180 EUR. A train trip from Paris to Strasbourg costs 75-85 EUR. But if you buy in advance, Paris-Nice is around 25 EUR in 2nd class and Paris-Strasbourg starts around 25 EUR as well. Good discounts on train travel exist for travelers under 26-years-old. A different option, which takes longer but costs less money, is Megabus/FlixBus. A bus trip from Paris to Marseille, for example, will cost around 30 EUR while a trip from Paris to Strasbourg costs 17-24 EUR. Local transit systems are reliable and cost between 1-3 EUR per trip. Transportation to and from the airport into the city center is generally affordable and user-friendly. Expect about 10 EUR to get to Paris from Charles de Gaulle. Taxis will be tough on the budget, so avoid when you can.

Activities – Wine tours will be your priciest activity at around 90 EUR per day. Most attractions and museum entrance fees cost between 9-20 EUR. Going up the Eiffel Tower will cost between 7-17 EUR. Visiting the Versailles Palace and Gardens will cost 25 EUR.

Suggested daily budget – 45-75 EUR / $46-76 USD (Note: This is a suggested budget assuming you’re staying in a hostel, eating out a little, cooking most of your meals, and using local transportation. Using the budget tips below, you can always lower this number. However, if you stay in fancier accommodation or eat out more often, expect this to be higher!)", title: "Paris, France", image: open("https://i.gocollette.com/img/destination-page/europe/france/france-ms1.jpg?h=720&w=1280&la=en")}
])

Comment.create ([
	{post_id: 1, user_id: 1, comment: "This is a comment"},
	{post_id: 2, user_id: 2, comment: "Another comment"}
])